const route=require("express").Router()
const {teacherMiddleware,studentMiddleware}=require("../middleware/studAndTeach.middleware")
const {addProfile,adminSignIn,sendOtp,otpVerify,LoadUser} =require("../auth/auth")
route.post("/auth/admin/add",addProfile)
route.post("/auth/teacher/add",addProfile)
route.post("/auth/student/add",addProfile)
route.post("/auth/admin/signin",adminSignIn)
route.post("/auth/teacher/otp",teacherMiddleware,sendOtp)
route.post("/auth/student/otp",studentMiddleware,sendOtp)
route.post("/auth/verify/otp/:verifyToken",otpVerify)
route.post("/auth/student/otp",studentMiddleware,sendOtp)
route.get("/auth/load/user",LoadUser)
module.exports=route